/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/estimators/kalman/invariant_ekf.h
/// @brief Initial-wave fail-closed module outline for INVARIANT_EKF.
#ifndef UEF_UCON_SCAFFOLD_INVARIANT_EKF_H
#define UEF_UCON_SCAFFOLD_INVARIANT_EKF_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Lie-group-aware invariant error model; distinct from an iterated EKF.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: FIRST_PASS.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check group state and invariant error convention.
/// TODO(INVARIANT_EKF.validate_model): Pin left/right error and frame conventions.
/// Algorithm-specific focus: Lie-group-aware invariant
/// error model; distinct from an iterated EKF.
ucon_status_t ucon_invariant_ekf_validate_model(const ucon_algorithm_scaffold_call_t *call);

/// Initialize group-valued state and tangent covariance.
/// TODO(INVARIANT_EKF.init): Validate the group representation and covariance coordinates.
/// Algorithm-specific focus: Lie-group-aware invariant error model;
/// distinct from an iterated EKF.
ucon_status_t ucon_invariant_ekf_init(const ucon_algorithm_scaffold_call_t *call);

/// Reset covariance and invariant error history.
/// TODO(INVARIANT_EKF.reset): Specify nominal group-state retention. Algorithm-specific
/// focus: Lie-group-aware invariant error model; distinct from an
/// iterated EKF.
ucon_status_t ucon_invariant_ekf_reset(const ucon_algorithm_scaffold_call_t *call);

/// Propagate group state and invariant covariance.
/// TODO(INVARIANT_EKF.predict): Derive dynamics/Jacobians for the selected invariant
/// convention. Algorithm-specific focus: Lie-group-aware
/// invariant error model; distinct from an iterated EKF.
ucon_status_t ucon_invariant_ekf_predict(const ucon_algorithm_scaffold_call_t *call);

/// Apply innovation in tangent coordinates and inject correction.
/// TODO(INVARIANT_EKF.correct): Define residual mapping and covariance reset.
/// Algorithm-specific focus: Lie-group-aware invariant error
/// model; distinct from an iterated EKF.
ucon_status_t ucon_invariant_ekf_correct(const ucon_algorithm_scaffold_call_t *call);

/// Run invariant prediction and correction.
/// TODO(INVARIANT_EKF.step): Do not substitute iterated-EKF equations. Algorithm-specific
/// focus: Lie-group-aware invariant error model; distinct from an
/// iterated EKF.
ucon_status_t ucon_invariant_ekf_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_INVARIANT_EKF_H */
