/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/estimators/kalman/iterated_ekf.h
/// @brief Initial-wave fail-closed module outline for ITERATED_EKF.
#ifndef UEF_UCON_SCAFFOLD_ITERATED_EKF_H
#define UEF_UCON_SCAFFOLD_ITERATED_EKF_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// EKF + inner Newton iteration for measurement update
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: PLANNED.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Validate nonlinear models and fixed correction-iteration limit.
/// TODO(ITERATED_EKF.validate_model): Define Jacobian evaluation and convergence tolerance.
/// Algorithm-specific focus: EKF + inner Newton iteration
/// for measurement update
ucon_status_t ucon_iterated_ekf_validate_model(const ucon_algorithm_scaffold_call_t *call);

/// Initialize estimate and covariance.
/// TODO(ITERATED_EKF.init): Define prior for each measurement update. Algorithm-specific
/// focus: EKF + inner Newton iteration for measurement update
ucon_status_t ucon_iterated_ekf_init(const ucon_algorithm_scaffold_call_t *call);

/// Reset filter history.
/// TODO(ITERATED_EKF.reset): Specify model-context retention. Algorithm-specific focus: EKF +
/// inner Newton iteration for measurement update
ucon_status_t ucon_iterated_ekf_reset(const ucon_algorithm_scaffold_call_t *call);

/// Propagate prior estimate/covariance once per sample.
/// TODO(ITERATED_EKF.predict): Do not repeat process propagation inside measurement
/// iteration. Algorithm-specific focus: EKF + inner Newton
/// iteration for measurement update
ucon_status_t ucon_iterated_ekf_predict(const ucon_algorithm_scaffold_call_t *call);

/// Re-linearize and refine the same measurement update to convergence/limit.
/// TODO(ITERATED_EKF.iterate_measurement): Define damping, iteration cap, and no-convergence
/// result. Algorithm-specific focus: EKF + inner
/// Newton iteration for measurement update
ucon_status_t ucon_iterated_ekf_iterate_measurement(const ucon_algorithm_scaffold_call_t *call);

/// Commit final correction and covariance once iteration terminates acceptably.
/// TODO(ITERATED_EKF.commit_correction): Preserve prior on rejected/nonconverged update
/// unless policy states otherwise. Algorithm-specific
/// focus: EKF + inner Newton iteration for measurement
/// update
ucon_status_t ucon_iterated_ekf_commit_correction(const ucon_algorithm_scaffold_call_t *call);

/// Run prediction and bounded iterated correction.
/// TODO(ITERATED_EKF.step): Expose iteration count and convergence status. Algorithm-specific
/// focus: EKF + inner Newton iteration for measurement update
ucon_status_t ucon_iterated_ekf_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_ITERATED_EKF_H */
