/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/estimators/kalman/sqrt_ukf.h
/// @brief Initial-wave fail-closed module outline for SQRT_UKF.
#ifndef UEF_UCON_SCAFFOLD_SQRT_UKF_H
#define UEF_UCON_SCAFFOLD_SQRT_UKF_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Square-root UKF; most numerically stable
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: PLANNED.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Validate the unscented model, scaled weights, and square-root convention.
/// TODO(SQRT_UKF.validate_model): 1) Pin factor orientation and the declared scaled-point
/// rule/weights. 2) Check dimensions, finite noise factors,
/// c=n+lambda, and fixed point workspace. 3) Define handling
/// for negative covariance weights and rank loss before
/// changing state. Algorithm-specific focus: Square-root UKF;
/// most numerically stable
ucon_status_t ucon_sqrt_ukf_validate_model(const ucon_algorithm_scaffold_call_t *call);

/// Initialize the estimate, covariance factor, weights, and fixed point workspace.
/// TODO(SQRT_UKF.init): 1) Validate x0/P0 and factor P0 using the pinned orientation. 2)
/// Compute scaled weights and ensure every required QR/downdate
/// workspace is bounded. 3) Initialize timestamp/diagnostics and publish
/// only after all checks succeed. Algorithm-specific focus: Square-root
/// UKF; most numerically stable
ucon_status_t ucon_sqrt_ukf_init(const ucon_algorithm_scaffold_call_t *call);

/// Reset estimate/factor while retaining the selected sigma-point configuration.
/// TODO(SQRT_UKF.reset): 1) Clear timestamp, freshness, and innovation history. 2) Restore
/// caller seeds and refactor covariance without changing scaling/weight
/// parameters. 3) Commit nominal state and factor atomically.
/// Algorithm-specific focus: Square-root UKF; most numerically stable
ucon_status_t ucon_sqrt_ukf_reset(const ucon_algorithm_scaffold_call_t *call);

/// Generate scaled sigma points from the square-root factor.
/// TODO(SQRT_UKF.generate_sigma_points): 1) Compute c=n+lambda and scale the triangular
/// factor by sqrt(c). 2) Emit the central point and
/// paired plus/minus factor-column points in fixed
/// order. 3) Assign configured mean/covariance weights
/// and reject invalid c, nonfinite points, or
/// unsupported negative-weight policy.
/// Algorithm-specific focus: Square-root UKF; most
/// numerically stable
ucon_status_t ucon_sqrt_ukf_generate_sigma_points(const ucon_algorithm_scaffold_call_t *call);

/// Propagate sigma points and recover predicted covariance factor by QR/downdate.
/// TODO(SQRT_UKF.predict_factor): 1) Evaluate the process model for each sigma point and
/// compute the weighted mean. 2) Stack weighted deviation
/// columns with the process-noise factor and QR-factor for
/// positive covariance weights. 3) Apply bounded rank-one
/// Cholesky updates/downdates for signed weights; reject
/// failed downdates and commit only a valid factor.
/// Algorithm-specific focus: Square-root UKF; most numerically
/// stable
ucon_status_t ucon_sqrt_ukf_predict_factor(const ucon_algorithm_scaffold_call_t *call);

/// Apply the measurement transform, innovation gate, and square-root update.
/// TODO(SQRT_UKF.correct_factor): 1) Transform sigma points through h and compute weighted
/// measurement mean/cross covariance. 2) Build innovation
/// factor from weighted deviations and measurement-noise
/// factor, then solve triangular systems for gain/NIS. 3) Gate
/// and downdate state factor using the declared signed-weight
/// policy; preserve prediction on rank/numeric failure.
/// Algorithm-specific focus: Square-root UKF; most numerically
/// stable
ucon_status_t ucon_sqrt_ukf_correct_factor(const ucon_algorithm_scaffold_call_t *call);

/// Run one square-root unscented predict/correct cycle.
/// TODO(SQRT_UKF.step): 1) Validate timestamp and generate the configured scaled points. 2)
/// Predict once and stage the QR/downdate factor. 3) Correct only
/// present channels with triangular solves. 4) Commit
/// state/factor/diagnostics together; do not form an unchecked full
/// covariance as a shortcut. Algorithm-specific focus: Square-root UKF;
/// most numerically stable
ucon_status_t ucon_sqrt_ukf_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_SQRT_UKF_H */
