/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/estimators/kalman/ukf_merwe.h
/// @brief Initial-wave fail-closed module outline for UKF_MERWE.
#ifndef UEF_UCON_SCAFFOLD_UKF_MERWE_H
#define UEF_UCON_SCAFFOLD_UKF_MERWE_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Van der Merwe scaled sigma-point parameterization of the UKF; share the UKF runtime kernel only if the weight and spread contract stays explicit.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: FIRST_PASS.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check nonlinear models and Merwe sigma-point configuration.
/// TODO(UKF_MERWE.validate_model): Pin alpha, beta, kappa, state dimension, and admissible
/// weights. Algorithm-specific focus: Van der Merwe scaled
/// sigma-point parameterization of the UKF; share the UKF
/// runtime kernel only if the weight and spread contract
/// stays explicit.
ucon_status_t ucon_ukf_merwe_validate_model(const ucon_algorithm_scaffold_call_t *call);

/// Initialize estimate, covariance, and sigma workspace.
/// TODO(UKF_MERWE.init): Define covariance factorization failure. Algorithm-specific focus:
/// Van der Merwe scaled sigma-point parameterization of the UKF; share
/// the UKF runtime kernel only if the weight and spread contract stays
/// explicit.
ucon_status_t ucon_ukf_merwe_init(const ucon_algorithm_scaffold_call_t *call);

/// Reset estimate/covariance history.
/// TODO(UKF_MERWE.reset): Specify retained configuration/context. Algorithm-specific focus:
/// Van der Merwe scaled sigma-point parameterization of the UKF; share
/// the UKF runtime kernel only if the weight and spread contract stays
/// explicit.
ucon_status_t ucon_ukf_merwe_reset(const ucon_algorithm_scaffold_call_t *call);

/// Generate van der Merwe scaled sigma points and weights.
/// TODO(UKF_MERWE.generate_merwe_points): Follow the declared scaling convention and
/// state-dimension factor. Algorithm-specific focus:
/// Van der Merwe scaled sigma-point parameterization
/// of the UKF; share the UKF runtime kernel only if
/// the weight and spread contract stays explicit.
ucon_status_t ucon_ukf_merwe_generate_merwe_points(const ucon_algorithm_scaffold_call_t *call);

/// Propagate sigma points through the process model.
/// TODO(UKF_MERWE.predict): Define noise augmentation and covariance recovery.
/// Algorithm-specific focus: Van der Merwe scaled sigma-point
/// parameterization of the UKF; share the UKF runtime kernel only if
/// the weight and spread contract stays explicit.
ucon_status_t ucon_ukf_merwe_predict(const ucon_algorithm_scaffold_call_t *call);

/// Apply measurement transform and update estimate/covariance.
/// TODO(UKF_MERWE.correct): Define innovation solve, gating, and conditioning.
/// Algorithm-specific focus: Van der Merwe scaled sigma-point
/// parameterization of the UKF; share the UKF runtime kernel only if
/// the weight and spread contract stays explicit.
ucon_status_t ucon_ukf_merwe_correct(const ucon_algorithm_scaffold_call_t *call);

/// Run one Merwe-parameterized UKF cycle.
/// TODO(UKF_MERWE.step): Share implementation with UKF only if semantics remain explicit.
/// Algorithm-specific focus: Van der Merwe scaled sigma-point
/// parameterization of the UKF; share the UKF runtime kernel only if
/// the weight and spread contract stays explicit.
ucon_status_t ucon_ukf_merwe_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_UKF_MERWE_H */
