/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/control/predictive/ilqr.h
/// @brief Initial-wave fail-closed module outline for ILQR.
#ifndef UEF_UCON_SCAFFOLD_ILQR_H
#define UEF_UCON_SCAFFOLD_ILQR_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Iterative LQR; backward pass + forward pass
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: PLANNED.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check plant, horizon, objective, constraints, and solver contract.
/// TODO(ILQR.validate_problem): Reject inconsistent bounds and define fixed memory/iteration
/// budgets. Algorithm-specific focus: Iterative LQR; backward
/// pass + forward pass
ucon_status_t ucon_ilqr_validate_problem(const ucon_algorithm_scaffold_call_t *call);

/// Initialize warm start, references, and solver workspace.
/// TODO(ILQR.init): Define first-solve seed and caller-owned data. Algorithm-specific focus:
/// Iterative LQR; backward pass + forward pass
ucon_status_t ucon_ilqr_init(const ucon_algorithm_scaffold_call_t *call);

/// Clear warm-start, disturbance, and optimizer history.
/// TODO(ILQR.reset): Specify reusable factorization/active-set behavior. Algorithm-specific
/// focus: Iterative LQR; backward pass + forward pass
ucon_status_t ucon_ilqr_reset(const ucon_algorithm_scaffold_call_t *call);

/// Build/update the finite-horizon prediction and optimization problem.
/// TODO(ILQR.prepare_problem): State discretization, terminal conditions, scaling, and time
/// budget. Algorithm-specific focus: Iterative LQR; backward pass
/// + forward pass
ucon_status_t ucon_ilqr_prepare_problem(const ucon_algorithm_scaffold_call_t *call);

/// Run the selected bounded optimization method.
/// TODO(ILQR.solve_problem): Report infeasible, nonconverged, numeric, and iteration-limit
/// outcomes distinctly. Algorithm-specific focus: Iterative LQR;
/// backward pass + forward pass
ucon_status_t ucon_ilqr_solve_problem(const ucon_algorithm_scaffold_call_t *call);

/// Check candidate bounds and configured residual tolerances.
/// TODO(ILQR.verify_solution): Never apply an unchecked solution or hide a missed deadline.
/// Algorithm-specific focus: Iterative LQR; backward pass +
/// forward pass
ucon_status_t ucon_ilqr_verify_solution(const ucon_algorithm_scaffold_call_t *call);

/// Prepare, solve, verify, and publish the first admissible input.
/// TODO(ILQR.step): Fallback must be caller-configured; do not invent a command.
/// Algorithm-specific focus: Iterative LQR; backward pass + forward pass
ucon_status_t ucon_ilqr_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_ILQR_H */
