/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/control/predictive/zone_mpc.h
/// @brief Initial-wave fail-closed module outline for ZONE_MPC.
#ifndef UEF_UCON_SCAFFOLD_ZONE_MPC_H
#define UEF_UCON_SCAFFOLD_ZONE_MPC_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Zone tracking; relaxed terminal set
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: PLANNED.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check plant, horizon, objective, constraints, and solver contract.
/// TODO(ZONE_MPC.validate_problem): Reject inconsistent bounds and define fixed
/// memory/iteration budgets. Algorithm-specific focus: Zone
/// tracking; relaxed terminal set
ucon_status_t ucon_zone_mpc_validate_problem(const ucon_algorithm_scaffold_call_t *call);

/// Initialize warm start, references, and solver workspace.
/// TODO(ZONE_MPC.init): Define first-solve seed and caller-owned data. Algorithm-specific
/// focus: Zone tracking; relaxed terminal set
ucon_status_t ucon_zone_mpc_init(const ucon_algorithm_scaffold_call_t *call);

/// Clear warm-start, disturbance, and optimizer history.
/// TODO(ZONE_MPC.reset): Specify reusable factorization/active-set behavior.
/// Algorithm-specific focus: Zone tracking; relaxed terminal set
ucon_status_t ucon_zone_mpc_reset(const ucon_algorithm_scaffold_call_t *call);

/// Build/update the finite-horizon prediction and optimization problem.
/// TODO(ZONE_MPC.prepare_problem): State discretization, terminal conditions, scaling, and
/// time budget. Algorithm-specific focus: Zone tracking;
/// relaxed terminal set
ucon_status_t ucon_zone_mpc_prepare_problem(const ucon_algorithm_scaffold_call_t *call);

/// Run the selected bounded optimization method.
/// TODO(ZONE_MPC.solve_problem): Report infeasible, nonconverged, numeric, and
/// iteration-limit outcomes distinctly. Algorithm-specific
/// focus: Zone tracking; relaxed terminal set
ucon_status_t ucon_zone_mpc_solve_problem(const ucon_algorithm_scaffold_call_t *call);

/// Check candidate bounds and configured residual tolerances.
/// TODO(ZONE_MPC.verify_solution): Never apply an unchecked solution or hide a missed
/// deadline. Algorithm-specific focus: Zone tracking; relaxed
/// terminal set
ucon_status_t ucon_zone_mpc_verify_solution(const ucon_algorithm_scaffold_call_t *call);

/// Prepare, solve, verify, and publish the first admissible input.
/// TODO(ZONE_MPC.step): Fallback must be caller-configured; do not invent a command.
/// Algorithm-specific focus: Zone tracking; relaxed terminal set
ucon_status_t ucon_zone_mpc_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_ZONE_MPC_H */
