/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/infrastructure/blocks/signal_validity.h
/// @brief Initial-wave fail-closed module outline for SIGNAL_VALIDITY.
#ifndef UEF_UCON_SCAFFOLD_SIGNAL_VALIDITY_H
#define UEF_UCON_SCAFFOLD_SIGNAL_VALIDITY_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Range/staleness/finiteness checks and configured redundant-sensor voting.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: FIRST_PASS.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check port counts, dimensions, bounds, and scheduling/reset rules.
/// TODO(SIGNAL_VALIDITY.validate_config): Define ordering and meaning of every port.
/// Algorithm-specific focus:
/// Range/staleness/finiteness checks and configured
/// redundant-sensor voting.
ucon_status_t ucon_signal_validity_validate_config(const ucon_algorithm_scaffold_call_t *call);

/// Initialize bounded block state and caller-selected values.
/// TODO(SIGNAL_VALIDITY.init): Specify deterministic startup. Algorithm-specific focus:
/// Range/staleness/finiteness checks and configured
/// redundant-sensor voting.
ucon_status_t ucon_signal_validity_init(const ucon_algorithm_scaffold_call_t *call);

/// Clear or preload state according to exact block semantics.
/// TODO(SIGNAL_VALIDITY.reset): Define reset priority with a simultaneous sample.
/// Algorithm-specific focus: Range/staleness/finiteness checks
/// and configured redundant-sensor voting.
ucon_status_t ucon_signal_validity_reset(const ucon_algorithm_scaffold_call_t *call);

/// Evaluate block law for the declared mode and sample timing.
/// TODO(SIGNAL_VALIDITY.compute_output): Define saturation and non-finite handling.
/// Algorithm-specific focus: Range/staleness/finiteness
/// checks and configured redundant-sensor voting.
ucon_status_t ucon_signal_validity_compute_output(const ucon_algorithm_scaffold_call_t *call);

/// Process one invocation and publish outputs/status.
/// TODO(SIGNAL_VALIDITY.step): Avoid hidden scheduling, allocation, or cross-instance state.
/// Algorithm-specific focus: Range/staleness/finiteness checks
/// and configured redundant-sensor voting.
ucon_status_t ucon_signal_validity_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_SIGNAL_VALIDITY_H */
