/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/control/nonlinear/feedback_lin.h
/// @brief Initial-wave fail-closed module outline for FEEDBACK_LIN.
#ifndef UEF_UCON_SCAFFOLD_FEEDBACK_LIN_H
#define UEF_UCON_SCAFFOLD_FEEDBACK_LIN_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Exact feedback linearisation; needs `{{INVERSE_DYNAMICS}}` block
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: PLANNED.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check nonlinear model, surface/relative-degree data, and parameter bounds.
/// TODO(FEEDBACK_LIN.validate_model): Implementation sequence: 1) Validate pointers,
/// configuration, dimensions, and preconditions before
/// writing outputs or state. 2) Check nonlinear model,
/// surface/relative-degree data, and parameter bounds. 3)
/// Check numeric results, declared constraints, and fixed
/// work/memory bounds. 4) Commit outputs, state, and
/// diagnostics together only after success; preserve prior
/// values on failure. Operation-specific requirements:
/// State operating-region and uncertainty assumptions.
/// Algorithm-specific focus: Exact feedback linearisation;
/// needs `{{INVERSE_DYNAMICS}}` block
ucon_status_t ucon_feedback_lin_validate_model(const ucon_algorithm_scaffold_call_t *call);

/// Initialize virtual-control, adaptation, integral, and filter state.
/// TODO(FEEDBACK_LIN.init): Implementation sequence: 1) Validate pointers, configuration,
/// dimensions, and preconditions before writing outputs or state. 2)
/// Initialize virtual-control, adaptation, integral, and filter
/// state. 3) Check numeric results, declared constraints, and fixed
/// work/memory bounds. 4) Commit outputs, state, and diagnostics
/// together only after success; preserve prior values on failure.
/// Operation-specific requirements: Define state seeds and bound
/// startup transients. Algorithm-specific focus: Exact feedback
/// linearisation; needs `{{INVERSE_DYNAMICS}}` block
ucon_status_t ucon_feedback_lin_init(const ucon_algorithm_scaffold_call_t *call);

/// Reset controller/adaptation history.
/// TODO(FEEDBACK_LIN.reset): Implementation sequence: 1) Validate pointers, configuration,
/// dimensions, and preconditions before writing outputs or state.
/// 2) Reset controller/adaptation history. 3) Check numeric
/// results, declared constraints, and fixed work/memory bounds. 4)
/// Commit outputs, state, and diagnostics together only after
/// success; preserve prior values on failure. Operation-specific
/// requirements: Specify parameter projection and bumpless restart.
/// Algorithm-specific focus: Exact feedback linearisation; needs
/// `{{INVERSE_DYNAMICS}}` block
ucon_status_t ucon_feedback_lin_reset(const ucon_algorithm_scaffold_call_t *call);

/// Evaluate tracking error, surface, barrier, or Lyapunov terms.
/// TODO(FEEDBACK_LIN.compute_surface): Implementation sequence: 1) Validate pointers,
/// configuration, dimensions, and preconditions before
/// writing outputs or state. 2) Evaluate tracking error,
/// surface, barrier, or Lyapunov terms. 3) Check numeric
/// results, declared constraints, and fixed work/memory
/// bounds. 4) Commit outputs, state, and diagnostics
/// together only after success; preserve prior values on
/// failure. Operation-specific requirements: Declare
/// sign, units, derivative source, and singularity
/// handling. Algorithm-specific focus: Exact feedback
/// linearisation; needs `{{INVERSE_DYNAMICS}}` block
ucon_status_t ucon_feedback_lin_compute_surface(const ucon_algorithm_scaffold_call_t *call);

/// Compute the method-specific bounded control candidate.
/// TODO(FEEDBACK_LIN.compute_control): Implementation sequence: 1) Validate pointers,
/// configuration, dimensions, and preconditions before
/// writing outputs or state. 2) Compute the
/// method-specific bounded control candidate. 3) Check
/// numeric results, declared constraints, and fixed
/// work/memory bounds. 4) Commit outputs, state, and
/// diagnostics together only after success; preserve
/// prior values on failure. Operation-specific
/// requirements: Define actuator limits and
/// chattering/boundary-layer policy. Algorithm-specific
/// focus: Exact feedback linearisation; needs
/// `{{INVERSE_DYNAMICS}}` block
ucon_status_t ucon_feedback_lin_compute_control(const ucon_algorithm_scaffold_call_t *call);

/// Run one deterministic control update and report status/diagnostics.
/// TODO(FEEDBACK_LIN.step): Implementation sequence: 1) Validate pointers, configuration,
/// dimensions, and preconditions before writing outputs or state. 2)
/// Run one deterministic control update and report
/// status/diagnostics. 3) Check numeric results, declared
/// constraints, and fixed work/memory bounds. 4) Commit outputs,
/// state, and diagnostics together only after success; preserve
/// prior values on failure. Operation-specific requirements: Commit
/// state only after numeric and constraint checks succeed.
/// Algorithm-specific focus: Exact feedback linearisation; needs
/// `{{INVERSE_DYNAMICS}}` block
ucon_status_t ucon_feedback_lin_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_FEEDBACK_LIN_H */
