/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/control/nonlinear/flatness.h
/// @brief Initial-wave fail-closed module outline for FLATNESS.
#ifndef UEF_UCON_SCAFFOLD_FLATNESS_H
#define UEF_UCON_SCAFFOLD_FLATNESS_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Flatness-based trajectory tracking
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: PLANNED.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check nonlinear model, surface/relative-degree data, and parameter bounds.
/// TODO(FLATNESS.validate_model): State operating-region and uncertainty assumptions.
/// Algorithm-specific focus: Flatness-based trajectory
/// tracking
ucon_status_t ucon_flatness_validate_model(const ucon_algorithm_scaffold_call_t *call);

/// Initialize virtual-control, adaptation, integral, and filter state.
/// TODO(FLATNESS.init): Define state seeds and bound startup transients. Algorithm-specific
/// focus: Flatness-based trajectory tracking
ucon_status_t ucon_flatness_init(const ucon_algorithm_scaffold_call_t *call);

/// Reset controller/adaptation history.
/// TODO(FLATNESS.reset): Specify parameter projection and bumpless restart.
/// Algorithm-specific focus: Flatness-based trajectory tracking
ucon_status_t ucon_flatness_reset(const ucon_algorithm_scaffold_call_t *call);

/// Evaluate tracking error, surface, barrier, or Lyapunov terms.
/// TODO(FLATNESS.compute_surface): Declare sign, units, derivative source, and singularity
/// handling. Algorithm-specific focus: Flatness-based
/// trajectory tracking
ucon_status_t ucon_flatness_compute_surface(const ucon_algorithm_scaffold_call_t *call);

/// Compute the method-specific bounded control candidate.
/// TODO(FLATNESS.compute_control): Define actuator limits and chattering/boundary-layer
/// policy. Algorithm-specific focus: Flatness-based
/// trajectory tracking
ucon_status_t ucon_flatness_compute_control(const ucon_algorithm_scaffold_call_t *call);

/// Run one deterministic control update and report status/diagnostics.
/// TODO(FLATNESS.step): Commit state only after numeric and constraint checks succeed.
/// Algorithm-specific focus: Flatness-based trajectory tracking
ucon_status_t ucon_flatness_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_FLATNESS_H */
