/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/control/nonlinear/ndi.h
/// @brief Initial-wave fail-closed module outline for NDI.
#ifndef UEF_UCON_SCAFFOLD_NDI_H
#define UEF_UCON_SCAFFOLD_NDI_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Nonlinear and incremental dynamic inversion; aerospace-oriented first-pass targets.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: FIRST_PASS.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check nonlinear model, surface/relative-degree data, and parameter bounds.
/// TODO(NDI.validate_model): State operating-region and uncertainty assumptions.
/// Algorithm-specific focus: Nonlinear and incremental dynamic
/// inversion; aerospace-oriented first-pass targets.
ucon_status_t ucon_ndi_validate_model(const ucon_algorithm_scaffold_call_t *call);

/// Initialize virtual-control, adaptation, integral, and filter state.
/// TODO(NDI.init): Define state seeds and bound startup transients. Algorithm-specific focus:
/// Nonlinear and incremental dynamic inversion; aerospace-oriented first-pass
/// targets.
ucon_status_t ucon_ndi_init(const ucon_algorithm_scaffold_call_t *call);

/// Reset controller/adaptation history.
/// TODO(NDI.reset): Specify parameter projection and bumpless restart. Algorithm-specific
/// focus: Nonlinear and incremental dynamic inversion; aerospace-oriented
/// first-pass targets.
ucon_status_t ucon_ndi_reset(const ucon_algorithm_scaffold_call_t *call);

/// Evaluate tracking error, surface, barrier, or Lyapunov terms.
/// TODO(NDI.compute_surface): Declare sign, units, derivative source, and singularity
/// handling. Algorithm-specific focus: Nonlinear and incremental
/// dynamic inversion; aerospace-oriented first-pass targets.
ucon_status_t ucon_ndi_compute_surface(const ucon_algorithm_scaffold_call_t *call);

/// Compute the method-specific bounded control candidate.
/// TODO(NDI.compute_control): Define actuator limits and chattering/boundary-layer policy.
/// Algorithm-specific focus: Nonlinear and incremental dynamic
/// inversion; aerospace-oriented first-pass targets.
ucon_status_t ucon_ndi_compute_control(const ucon_algorithm_scaffold_call_t *call);

/// Run one deterministic control update and report status/diagnostics.
/// TODO(NDI.step): Commit state only after numeric and constraint checks succeed.
/// Algorithm-specific focus: Nonlinear and incremental dynamic inversion;
/// aerospace-oriented first-pass targets.
ucon_status_t ucon_ndi_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_NDI_H */
