/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/control/scheduled/gain_schedule.h
/// @brief Initial-wave fail-closed module outline for GAIN_SCHEDULE.
#ifndef UEF_UCON_SCAFFOLD_GAIN_SCHEDULE_H
#define UEF_UCON_SCAFFOLD_GAIN_SCHEDULE_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Interpolation between configured linear controllers.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: FIRST_PASS.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check schedule grid, gain dimensions, and scheduling-variable bounds.
/// TODO(GAIN_SCHEDULE.validate_schedule): Define grid order, extrapolation, and compatible
/// controller modes. Algorithm-specific focus:
/// Interpolation between configured linear
/// controllers.
ucon_status_t ucon_gain_schedule_validate_schedule(const ucon_algorithm_scaffold_call_t *call);

/// Initialize active schedule cell and interpolation state.
/// TODO(GAIN_SCHEDULE.init): Define first selection without stale state. Algorithm-specific
/// focus: Interpolation between configured linear controllers.
ucon_status_t ucon_gain_schedule_init(const ucon_algorithm_scaffold_call_t *call);

/// Reset transition and hysteresis state.
/// TODO(GAIN_SCHEDULE.reset): Specify transition behavior after grid changes.
/// Algorithm-specific focus: Interpolation between configured
/// linear controllers.
ucon_status_t ucon_gain_schedule_reset(const ucon_algorithm_scaffold_call_t *call);

/// Interpolate/select gains from the declared scheduling variable.
/// TODO(GAIN_SCHEDULE.select_gains): Define interpolation, hysteresis, and numeric bounds.
/// Algorithm-specific focus: Interpolation between
/// configured linear controllers.
ucon_status_t ucon_gain_schedule_select_gains(const ucon_algorithm_scaffold_call_t *call);

/// Map controller state during a gain/mode transition.
/// TODO(GAIN_SCHEDULE.transfer_state): Define bumpless transfer and incompatible-state
/// handling. Algorithm-specific focus: Interpolation
/// between configured linear controllers.
ucon_status_t ucon_gain_schedule_transfer_state(const ucon_algorithm_scaffold_call_t *call);

/// Apply the scheduled controller and publish selected-cell diagnostics.
/// TODO(GAIN_SCHEDULE.step): Keep schedule selection separate from plant parameter
/// adaptation. Algorithm-specific focus: Interpolation between
/// configured linear controllers.
ucon_status_t ucon_gain_schedule_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_GAIN_SCHEDULE_H */
