/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/estimators/identification/rls.h
/// @brief Initial-wave fail-closed module outline for RLS.
#ifndef UEF_UCON_SCAFFOLD_RLS_H
#define UEF_UCON_SCAFFOLD_RLS_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Recursive least-squares parameter estimator with an explicit regressor, covariance initialization, and optional forgetting factor.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: FIRST_PASS.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check regressor dimension, covariance seed, forgetting factor, and bounds.
/// TODO(RLS.validate_config): Define lambda range and covariance conditioning assumptions.
/// Algorithm-specific focus: Recursive least-squares parameter
/// estimator with an explicit regressor, covariance
/// initialization, and optional forgetting factor.
ucon_status_t ucon_rls_validate_config(const ucon_algorithm_scaffold_call_t *call);

/// Initialize parameter vector and information/covariance matrix.
/// TODO(RLS.init): Define P0 scaling and parameter seeding. Algorithm-specific focus:
/// Recursive least-squares parameter estimator with an explicit regressor,
/// covariance initialization, and optional forgetting factor.
ucon_status_t ucon_rls_init(const ucon_algorithm_scaffold_call_t *call);

/// Reset recursive memory and diagnostics.
/// TODO(RLS.reset): Define parameter retention versus reinitialization. Algorithm-specific
/// focus: Recursive least-squares parameter estimator with an explicit
/// regressor, covariance initialization, and optional forgetting factor.
ucon_status_t ucon_rls_reset(const ucon_algorithm_scaffold_call_t *call);

/// Apply one gain, parameter, and covariance recursion.
/// TODO(RLS.update): Specify symmetrization, regularization, and parameter projection.
/// Algorithm-specific focus: Recursive least-squares parameter estimator
/// with an explicit regressor, covariance initialization, and optional
/// forgetting factor.
ucon_status_t ucon_rls_update(const ucon_algorithm_scaffold_call_t *call);

/// Report residual and excitation/conditioning status.
/// TODO(RLS.get_diagnostics): Do not claim identification under insufficient excitation.
/// Algorithm-specific focus: Recursive least-squares parameter
/// estimator with an explicit regressor, covariance
/// initialization, and optional forgetting factor.
ucon_status_t ucon_rls_get_diagnostics(const ucon_algorithm_scaffold_call_t *call);

/// Consume one regressor/output pair and atomically publish parameters.
/// TODO(RLS.step): Define invalid sample behavior and bounded update count.
/// Algorithm-specific focus: Recursive least-squares parameter estimator with
/// an explicit regressor, covariance initialization, and optional forgetting
/// factor.
ucon_status_t ucon_rls_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_RLS_H */
