/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/future/control/nonlinear/terminal_smc.h
/// @brief Future-wave fail-closed module outline for TERMINAL_SMC.
#ifndef UEF_UCON_SCAFFOLD_TERMINAL_SMC_H
#define UEF_UCON_SCAFFOLD_TERMINAL_SMC_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Terminal sliding mode; finite-time convergence
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: PLANNED.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check nonlinear model, surface/relative-degree data, and parameter bounds.
/// TODO(TERMINAL_SMC.validate_model): State operating-region and uncertainty assumptions.
/// Algorithm-specific focus: Terminal sliding mode;
/// finite-time convergence
ucon_status_t ucon_terminal_smc_validate_model(const ucon_algorithm_scaffold_call_t *call);

/// Initialize virtual-control, adaptation, integral, and filter state.
/// TODO(TERMINAL_SMC.init): Define state seeds and bound startup transients.
/// Algorithm-specific focus: Terminal sliding mode; finite-time
/// convergence
ucon_status_t ucon_terminal_smc_init(const ucon_algorithm_scaffold_call_t *call);

/// Reset controller/adaptation history.
/// TODO(TERMINAL_SMC.reset): Specify parameter projection and bumpless restart.
/// Algorithm-specific focus: Terminal sliding mode; finite-time
/// convergence
ucon_status_t ucon_terminal_smc_reset(const ucon_algorithm_scaffold_call_t *call);

/// Evaluate tracking error, surface, barrier, or Lyapunov terms.
/// TODO(TERMINAL_SMC.compute_surface): Declare sign, units, derivative source, and
/// singularity handling. Algorithm-specific focus:
/// Terminal sliding mode; finite-time convergence
ucon_status_t ucon_terminal_smc_compute_surface(const ucon_algorithm_scaffold_call_t *call);

/// Compute the method-specific bounded control candidate.
/// TODO(TERMINAL_SMC.compute_control): Define actuator limits and chattering/boundary-layer
/// policy. Algorithm-specific focus: Terminal sliding
/// mode; finite-time convergence
ucon_status_t ucon_terminal_smc_compute_control(const ucon_algorithm_scaffold_call_t *call);

/// Run one deterministic control update and report status/diagnostics.
/// TODO(TERMINAL_SMC.step): Commit state only after numeric and constraint checks succeed.
/// Algorithm-specific focus: Terminal sliding mode; finite-time
/// convergence
ucon_status_t ucon_terminal_smc_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_TERMINAL_SMC_H */
