/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/future/estimators/kalman/adaptive_kf.h
/// @brief Future-wave fail-closed module outline for ADAPTIVE_KF.
#ifndef UEF_UCON_SCAFFOLD_ADAPTIVE_KF_H
#define UEF_UCON_SCAFFOLD_ADAPTIVE_KF_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Adaptive Kalman filter with an explicitly bounded covariance or noise adaptation law.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: PLANNED.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check state/measurement dimensions, model callbacks, and covariance assumptions.
/// TODO(ADAPTIVE_KF.validate_model): Reject invalid shapes before state changes; specify PSD
/// and conditioning policy. Algorithm-specific focus:
/// Adaptive Kalman filter with an explicitly bounded
/// covariance or noise adaptation law.
ucon_status_t ucon_adaptive_kf_validate_model(const ucon_algorithm_scaffold_call_t *call);

/// Initialize estimate, covariance, and fixed workspace.
/// TODO(ADAPTIVE_KF.init): Define initial-state ownership, covariance seed, and factorization
/// failure. Algorithm-specific focus: Adaptive Kalman filter with an
/// explicitly bounded covariance or noise adaptation law.
ucon_status_t ucon_adaptive_kf_init(const ucon_algorithm_scaffold_call_t *call);

/// Reset estimator history under a documented seed policy.
/// TODO(ADAPTIVE_KF.reset): Specify whether nominal estimate/model context is retained.
/// Algorithm-specific focus: Adaptive Kalman filter with an
/// explicitly bounded covariance or noise adaptation law.
ucon_status_t ucon_adaptive_kf_reset(const ucon_algorithm_scaffold_call_t *call);

/// Propagate estimate and uncertainty over one declared interval.
/// TODO(ADAPTIVE_KF.predict): Define discretization, process-noise timing, and stable
/// covariance update. Algorithm-specific focus: Adaptive Kalman
/// filter with an explicitly bounded covariance or noise
/// adaptation law.
ucon_status_t ucon_adaptive_kf_predict(const ucon_algorithm_scaffold_call_t *call);

/// Apply a timestamped measurement and compute innovation diagnostics.
/// TODO(ADAPTIVE_KF.correct): Define gating, missing-channel behavior, and failure atomicity.
/// Algorithm-specific focus: Adaptive Kalman filter with an
/// explicitly bounded covariance or noise adaptation law.
ucon_status_t ucon_adaptive_kf_correct(const ucon_algorithm_scaffold_call_t *call);

/// Run prediction and optional correction in a fixed documented order.
/// TODO(ADAPTIVE_KF.step): Handle asynchronous samples explicitly; do not synthesize missing
/// measurements. Algorithm-specific focus: Adaptive Kalman filter
/// with an explicitly bounded covariance or noise adaptation law.
ucon_status_t ucon_adaptive_kf_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_ADAPTIVE_KF_H */
