/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/future/estimators/kalman/dual_kf.h
/// @brief Future-wave fail-closed module outline for DUAL_KF.
#ifndef UEF_UCON_SCAFFOLD_DUAL_KF_H
#define UEF_UCON_SCAFFOLD_DUAL_KF_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Dual estimation scheme that jointly tracks plant state and selected unknown parameters.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: PLANNED.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check state/parameter partition and coupled process/measurement models.
/// TODO(DUAL_KF.validate_partition): Implementation sequence: 1) Validate pointers,
/// configuration, dimensions, and preconditions before
/// writing outputs or state. 2) Check state/parameter
/// partition and coupled process/measurement models. 3)
/// Check numeric results, declared constraints, and fixed
/// work/memory bounds. 4) Commit outputs, state, and
/// diagnostics together only after success; preserve prior
/// values on failure. Operation-specific requirements:
/// Specify which unknown parameters are augmented and why
/// the joint model is observable. Algorithm-specific focus:
/// Dual estimation scheme that jointly tracks plant state
/// and selected unknown parameters.
ucon_status_t ucon_dual_kf_validate_partition(const ucon_algorithm_scaffold_call_t *call);

/// Initialize state/parameter estimates and covariance blocks.
/// TODO(DUAL_KF.init): Implementation sequence: 1) Validate pointers, configuration,
/// dimensions, and preconditions before writing outputs or state. 2)
/// Initialize state/parameter estimates and covariance blocks. 3) Check
/// numeric results, declared constraints, and fixed work/memory bounds.
/// 4) Commit outputs, state, and diagnostics together only after success;
/// preserve prior values on failure. Operation-specific requirements:
/// Define cross-covariance and parameter uncertainty seed.
/// Algorithm-specific focus: Dual estimation scheme that jointly tracks
/// plant state and selected unknown parameters.
ucon_status_t ucon_dual_kf_init(const ucon_algorithm_scaffold_call_t *call);

/// Reset joint estimation history.
/// TODO(DUAL_KF.reset): Implementation sequence: 1) Validate pointers, configuration,
/// dimensions, and preconditions before writing outputs or state. 2)
/// Reset joint estimation history. 3) Check numeric results, declared
/// constraints, and fixed work/memory bounds. 4) Commit outputs, state,
/// and diagnostics together only after success; preserve prior values on
/// failure. Operation-specific requirements: Specify retained plant
/// state versus parameter estimate. Algorithm-specific focus: Dual
/// estimation scheme that jointly tracks plant state and selected
/// unknown parameters.
ucon_status_t ucon_dual_kf_reset(const ucon_algorithm_scaffold_call_t *call);

/// Propagate physical state and parameter model.
/// TODO(DUAL_KF.predict_state_parameters): Implementation sequence: 1) Validate pointers,
/// configuration, dimensions, and preconditions
/// before writing outputs or state. 2) Propagate
/// physical state and parameter model. 3) Check
/// numeric results, declared constraints, and fixed
/// work/memory bounds. 4) Commit outputs, state, and
/// diagnostics together only after success; preserve
/// prior values on failure. Operation-specific
/// requirements: Pin parameter
/// random-walk/fixed-model assumption.
/// Algorithm-specific focus: Dual estimation scheme
/// that jointly tracks plant state and selected
/// unknown parameters.
ucon_status_t ucon_dual_kf_predict_state_parameters(const ucon_algorithm_scaffold_call_t *call);

/// Apply measurement information to state and parameter estimates.
/// TODO(DUAL_KF.correct_joint_estimate): Implementation sequence: 1) Validate pointers,
/// configuration, dimensions, and preconditions before
/// writing outputs or state. 2) Apply measurement
/// information to state and parameter estimates. 3)
/// Check numeric results, declared constraints, and
/// fixed work/memory bounds. 4) Commit outputs, state,
/// and diagnostics together only after success;
/// preserve prior values on failure. Operation-specific
/// requirements: Define coupling and prevent
/// unobservable drift. Algorithm-specific focus: Dual
/// estimation scheme that jointly tracks plant state
/// and selected unknown parameters.
ucon_status_t ucon_dual_kf_correct_joint_estimate(const ucon_algorithm_scaffold_call_t *call);

/// Run bounded joint estimation and publish observability diagnostics.
/// TODO(DUAL_KF.step): Implementation sequence: 1) Validate pointers, configuration,
/// dimensions, and preconditions before writing outputs or state. 2) Run
/// bounded joint estimation and publish observability diagnostics. 3)
/// Check numeric results, declared constraints, and fixed work/memory
/// bounds. 4) Commit outputs, state, and diagnostics together only after
/// success; preserve prior values on failure. Operation-specific
/// requirements: Do not imply parameter convergence without excitation.
/// Algorithm-specific focus: Dual estimation scheme that jointly tracks
/// plant state and selected unknown parameters.
ucon_status_t ucon_dual_kf_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_DUAL_KF_H */
