/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/future/estimators/kalman/robust_kf.h
/// @brief Future-wave fail-closed module outline for ROBUST_KF.
#ifndef UEF_UCON_SCAFFOLD_ROBUST_KF_H
#define UEF_UCON_SCAFFOLD_ROBUST_KF_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Robust Kalman estimation variant with a named bounded-influence or outlier-resistance rule.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: PLANNED.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check state/measurement dimensions, model callbacks, and covariance assumptions.
/// TODO(ROBUST_KF.validate_model): Reject invalid shapes before state changes; specify PSD
/// and conditioning policy. Algorithm-specific focus: Robust
/// Kalman estimation variant with a named bounded-influence
/// or outlier-resistance rule.
ucon_status_t ucon_robust_kf_validate_model(const ucon_algorithm_scaffold_call_t *call);

/// Initialize estimate, covariance, and fixed workspace.
/// TODO(ROBUST_KF.init): Define initial-state ownership, covariance seed, and factorization
/// failure. Algorithm-specific focus: Robust Kalman estimation variant
/// with a named bounded-influence or outlier-resistance rule.
ucon_status_t ucon_robust_kf_init(const ucon_algorithm_scaffold_call_t *call);

/// Reset estimator history under a documented seed policy.
/// TODO(ROBUST_KF.reset): Specify whether nominal estimate/model context is retained.
/// Algorithm-specific focus: Robust Kalman estimation variant with a
/// named bounded-influence or outlier-resistance rule.
ucon_status_t ucon_robust_kf_reset(const ucon_algorithm_scaffold_call_t *call);

/// Propagate estimate and uncertainty over one declared interval.
/// TODO(ROBUST_KF.predict): Define discretization, process-noise timing, and stable
/// covariance update. Algorithm-specific focus: Robust Kalman
/// estimation variant with a named bounded-influence or
/// outlier-resistance rule.
ucon_status_t ucon_robust_kf_predict(const ucon_algorithm_scaffold_call_t *call);

/// Apply a timestamped measurement and compute innovation diagnostics.
/// TODO(ROBUST_KF.correct): Define gating, missing-channel behavior, and failure atomicity.
/// Algorithm-specific focus: Robust Kalman estimation variant with a
/// named bounded-influence or outlier-resistance rule.
ucon_status_t ucon_robust_kf_correct(const ucon_algorithm_scaffold_call_t *call);

/// Run prediction and optional correction in a fixed documented order.
/// TODO(ROBUST_KF.step): Handle asynchronous samples explicitly; do not synthesize missing
/// measurements. Algorithm-specific focus: Robust Kalman estimation
/// variant with a named bounded-influence or outlier-resistance rule.
ucon_status_t ucon_robust_kf_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_ROBUST_KF_H */
