/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/future/estimators/kalman/ud_kf.h
/// @brief Future-wave fail-closed module outline for UD_KF.
#ifndef UEF_UCON_SCAFFOLD_UD_KF_H
#define UEF_UCON_SCAFFOLD_UD_KF_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// UD-factorized Kalman filter that propagates covariance as unit-upper and diagonal factors.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: PLANNED.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check linear model and U-D factor dimensions.
/// TODO(UD_KF.validate_model): Pin unit-upper/diagonal convention and pivot policy.
/// Algorithm-specific focus: UD-factorized Kalman filter that
/// propagates covariance as unit-upper and diagonal factors.
ucon_status_t ucon_ud_kf_validate_model(const ucon_algorithm_scaffold_call_t *call);

/// Initialize estimate and U-D covariance factors.
/// TODO(UD_KF.init): Define factor conversion/validation from caller covariance.
/// Algorithm-specific focus: UD-factorized Kalman filter that propagates
/// covariance as unit-upper and diagonal factors.
ucon_status_t ucon_ud_kf_init(const ucon_algorithm_scaffold_call_t *call);

/// Reset estimate and factors.
/// TODO(UD_KF.reset): Specify covariance retention. Algorithm-specific focus: UD-factorized
/// Kalman filter that propagates covariance as unit-upper and diagonal
/// factors.
ucon_status_t ucon_ud_kf_reset(const ucon_algorithm_scaffold_call_t *call);

/// Propagate covariance using the U-D factor recursion.
/// TODO(UD_KF.predict_factor): Specify process-noise factorization and positive diagonal
/// checks. Algorithm-specific focus: UD-factorized Kalman filter
/// that propagates covariance as unit-upper and diagonal factors.
ucon_status_t ucon_ud_kf_predict_factor(const ucon_algorithm_scaffold_call_t *call);

/// Apply measurement update directly to U-D factors.
/// TODO(UD_KF.correct_factor): Define scalar/vector measurement ordering and conditioning
/// policy. Algorithm-specific focus: UD-factorized Kalman filter
/// that propagates covariance as unit-upper and diagonal factors.
ucon_status_t ucon_ud_kf_correct_factor(const ucon_algorithm_scaffold_call_t *call);

/// Run one factorized linear Kalman cycle.
/// TODO(UD_KF.step): Avoid silently reconstructing and refactoring a full covariance.
/// Algorithm-specific focus: UD-factorized Kalman filter that propagates
/// covariance as unit-upper and diagonal factors.
ucon_status_t ucon_ud_kf_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_UD_KF_H */
