/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/estimators/attitude/quest.h
/// @brief Initial-wave fail-closed module outline for QUEST.
#ifndef UEF_UCON_SCAFFOLD_QUEST_H
#define UEF_UCON_SCAFFOLD_QUEST_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Attitude determination from vector observations.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: FIRST_PASS.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check at least two weighted non-collinear reference/observation pairs.
/// TODO(QUEST.validate_vectors): Define frame direction, vector normalization, weights, and
/// rank threshold. Algorithm-specific focus: Attitude
/// determination from vector observations.
ucon_status_t ucon_quest_validate_vectors(const ucon_algorithm_scaffold_call_t *call);

/// Initialize fixed-size attitude solution workspace.
/// TODO(QUEST.init): Define output representation and invalid-solution state.
/// Algorithm-specific focus: Attitude determination from vector
/// observations.
ucon_status_t ucon_quest_init(const ucon_algorithm_scaffold_call_t *call);

/// Clear solution/diagnostic state.
/// TODO(QUEST.reset): Specify whether vector configuration is retained. Algorithm-specific
/// focus: Attitude determination from vector observations.
ucon_status_t ucon_quest_reset(const ucon_algorithm_scaffold_call_t *call);

/// Build the weighted attitude-determination matrix.
/// TODO(QUEST.build_wahba_matrix): Pin convention and ensure input weights are
/// finite/nonnegative. Algorithm-specific focus: Attitude
/// determination from vector observations.
ucon_status_t ucon_quest_build_wahba_matrix(const ucon_algorithm_scaffold_call_t *call);

/// Solve the selected QUEST eigen/quaternion relation.
/// TODO(QUEST.solve_attitude): Specify iteration/eigenvalue method and deterministic
/// convergence bound. Algorithm-specific focus: Attitude
/// determination from vector observations.
ucon_status_t ucon_quest_solve_attitude(const ucon_algorithm_scaffold_call_t *call);

/// Check residual, normalization, and geometry quality.
/// TODO(QUEST.verify_solution): Return an explicit degenerate-vector status.
/// Algorithm-specific focus: Attitude determination from vector
/// observations.
ucon_status_t ucon_quest_verify_solution(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_QUEST_H */
