/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/control/state_space/lqr.h
/// @brief Initial-wave fail-closed module outline for LQR.
#ifndef UEF_UCON_SCAFFOLD_LQR_H
#define UEF_UCON_SCAFFOLD_LQR_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// LQR/LQI are state-feedback variants; LQG composes a linear estimator with a state-feedback law.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: FIRST_PASS.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check matrix dimensions, gain layout, and state/input units.
/// TODO(LQR.validate_config): Declare whether gain synthesis is offline or part of this
/// module. Algorithm-specific focus: LQR/LQI are state-feedback
/// variants; LQG composes a linear estimator with a state-feedback
/// law.
ucon_status_t ucon_lqr_validate_config(const ucon_algorithm_scaffold_call_t *call);

/// Initialize controller and optional integral/observer interface state.
/// TODO(LQR.init): Define initial-state requirements and workspace. Algorithm-specific focus:
/// LQR/LQI are state-feedback variants; LQG composes a linear estimator with
/// a state-feedback law.
ucon_status_t ucon_lqr_init(const ucon_algorithm_scaffold_call_t *call);

/// Reset dynamic control memory.
/// TODO(LQR.reset): Specify bumpless restart and estimator coordination. Algorithm-specific
/// focus: LQR/LQI are state-feedback variants; LQG composes a linear
/// estimator with a state-feedback law.
ucon_status_t ucon_lqr_reset(const ucon_algorithm_scaffold_call_t *call);

/// Evaluate the declared state/output-feedback law.
/// TODO(LQR.compute_feedback): Define reference/feedforward terms, sign, and saturation
/// order. Algorithm-specific focus: LQR/LQI are state-feedback
/// variants; LQG composes a linear estimator with a
/// state-feedback law.
ucon_status_t ucon_lqr_compute_feedback(const ucon_algorithm_scaffold_call_t *call);

/// Evaluate feedback and publish a bounded command.
/// TODO(LQR.step): Preserve output on dimension/numeric failure and state work bounds.
/// Algorithm-specific focus: LQR/LQI are state-feedback variants; LQG
/// composes a linear estimator with a state-feedback law.
ucon_status_t ucon_lqr_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_LQR_H */
