/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/estimators/bayesian/particle.h
/// @brief Initial-wave fail-closed module outline for PARTICLE.
#ifndef UEF_UCON_SCAFFOLD_PARTICLE_H
#define UEF_UCON_SCAFFOLD_PARTICLE_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Bootstrap particle filter with explicit particle propagation, likelihood weighting, normalization, resampling, and random-number policy.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: PLANNED.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check particle count, likelihood, dimensions, and random source.
/// TODO(PARTICLE.validate_model): Bound storage and specify reproducible random-stream
/// behavior. Algorithm-specific focus: Bootstrap particle
/// filter with explicit particle propagation, likelihood
/// weighting, normalization, resampling, and random-number
/// policy.
ucon_status_t ucon_particle_validate_model(const ucon_algorithm_scaffold_call_t *call);

/// Initialize particles and normalized prior weights.
/// TODO(PARTICLE.init): Define caller-supplied prior and invalid-particle failure.
/// Algorithm-specific focus: Bootstrap particle filter with explicit
/// particle propagation, likelihood weighting, normalization,
/// resampling, and random-number policy.
ucon_status_t ucon_particle_init(const ucon_algorithm_scaffold_call_t *call);

/// Reset population and resampling diagnostics.
/// TODO(PARTICLE.reset): Specify random stream reset/retention. Algorithm-specific focus:
/// Bootstrap particle filter with explicit particle propagation,
/// likelihood weighting, normalization, resampling, and random-number
/// policy.
ucon_status_t ucon_particle_reset(const ucon_algorithm_scaffold_call_t *call);

/// Propagate each particle through the process model.
/// TODO(PARTICLE.propagate_particles): Bound per-particle work and random draws.
/// Algorithm-specific focus: Bootstrap particle filter
/// with explicit particle propagation, likelihood
/// weighting, normalization, resampling, and
/// random-number policy.
ucon_status_t ucon_particle_propagate_particles(const ucon_algorithm_scaffold_call_t *call);

/// Apply likelihood and normalize weights stably.
/// TODO(PARTICLE.update_weights): Handle all-zero likelihood without inventing a prior.
/// Algorithm-specific focus: Bootstrap particle filter with
/// explicit particle propagation, likelihood weighting,
/// normalization, resampling, and random-number policy.
ucon_status_t ucon_particle_update_weights(const ucon_algorithm_scaffold_call_t *call);

/// Apply the named resampling method at the configured threshold.
/// TODO(PARTICLE.resample): Define deterministic order and scratch bounds. Algorithm-specific
/// focus: Bootstrap particle filter with explicit particle
/// propagation, likelihood weighting, normalization, resampling, and
/// random-number policy.
ucon_status_t ucon_particle_resample(const ucon_algorithm_scaffold_call_t *call);

/// Compute state and uncertainty summaries.
/// TODO(PARTICLE.summarize_estimate): Specify circular/manifold averaging where needed.
/// Algorithm-specific focus: Bootstrap particle filter
/// with explicit particle propagation, likelihood
/// weighting, normalization, resampling, and random-number
/// policy.
ucon_status_t ucon_particle_summarize_estimate(const ucon_algorithm_scaffold_call_t *call);

/// Run propagation, weighting, optional resampling, and summary.
/// TODO(PARTICLE.step): Do not partially replace the prior population on failure.
/// Algorithm-specific focus: Bootstrap particle filter with explicit
/// particle propagation, likelihood weighting, normalization,
/// resampling, and random-number policy.
ucon_status_t ucon_particle_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_PARTICLE_H */
