/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/future/estimators/diagnostics/innovation_monitor.h
/// @brief Future-wave fail-closed module outline for INNOVATION_MONITOR.
#ifndef UEF_UCON_SCAFFOLD_INNOVATION_MONITOR_H
#define UEF_UCON_SCAFFOLD_INNOVATION_MONITOR_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Monitor estimator innovations and covariance-normalized residuals for configured consistency limits.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: PLANNED.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check statistic scale, thresholds, and window/persistence limits.
/// TODO(INNOVATION_MONITOR.validate_config): Define units, warm-up, and threshold equality
/// behavior. Algorithm-specific focus: Monitor
/// estimator innovations and covariance-normalized
/// residuals for configured consistency limits.
ucon_status_t ucon_innovation_monitor_validate_config(const ucon_algorithm_scaffold_call_t *call);

/// Initialize statistic, counters, and baseline state.
/// TODO(INNOVATION_MONITOR.init): Define baseline ownership and startup grace period.
/// Algorithm-specific focus: Monitor estimator innovations and
/// covariance-normalized residuals for configured consistency
/// limits.
ucon_status_t ucon_innovation_monitor_init(const ucon_algorithm_scaffold_call_t *call);

/// Clear detector history and rearm according to policy.
/// TODO(INNOVATION_MONITOR.reset): State whether reset also clears the reference baseline.
/// Algorithm-specific focus: Monitor estimator innovations
/// and covariance-normalized residuals for configured
/// consistency limits.
ucon_status_t ucon_innovation_monitor_reset(const ucon_algorithm_scaffold_call_t *call);

/// Compute normalized residual or cumulative change statistic.
/// TODO(INNOVATION_MONITOR.update_statistic): Handle missing data and zero variance without
/// division by zero. Algorithm-specific focus:
/// Monitor estimator innovations and
/// covariance-normalized residuals for configured
/// consistency limits.
ucon_status_t ucon_innovation_monitor_update_statistic(const ucon_algorithm_scaffold_call_t *call);

/// Apply threshold, persistence, clear, and latch rules.
/// TODO(INNOVATION_MONITOR.update_decision): Separate detection from fault isolation or
/// safety action. Algorithm-specific focus: Monitor
/// estimator innovations and covariance-normalized
/// residuals for configured consistency limits.
ucon_status_t ucon_innovation_monitor_update_decision(const ucon_algorithm_scaffold_call_t *call);

/// Process one timestamped input and publish statistic/status.
/// TODO(INNOVATION_MONITOR.step): Keep counters bounded and preserve state on invalid input.
/// Algorithm-specific focus: Monitor estimator innovations and
/// covariance-normalized residuals for configured consistency
/// limits.
ucon_status_t ucon_innovation_monitor_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_INNOVATION_MONITOR_H */
