/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/electrical/motor_control/foc_current_control.h
/// @brief Initial-wave fail-closed module outline for FOC_CURRENT_CONTROL.
#ifndef UEF_UCON_SCAFFOLD_FOC_CURRENT_CONTROL_H
#define UEF_UCON_SCAFFOLD_FOC_CURRENT_CONTROL_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Field-oriented current-control composition with d/q regulators, decoupling, and modulation interfaces.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: FIRST_PASS.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check motor model, transform, sample timing, and current/voltage limits.
/// TODO(FOC_CURRENT_CONTROL.validate_config): State motor type and angle-source validity.
/// Algorithm-specific focus: Field-oriented
/// current-control composition with d/q
/// regulators, decoupling, and modulation
/// interfaces.
ucon_status_t ucon_foc_current_control_validate_config(const ucon_algorithm_scaffold_call_t *call);

/// Initialize d/q loops, flux/torque estimate, and modulation state.
/// TODO(FOC_CURRENT_CONTROL.init): Define alignment and sensor-offset ownership.
/// Algorithm-specific focus: Field-oriented current-control
/// composition with d/q regulators, decoupling, and
/// modulation interfaces.
ucon_status_t ucon_foc_current_control_init(const ucon_algorithm_scaffold_call_t *call);

/// Reset control/estimator history without issuing gate actions.
/// TODO(FOC_CURRENT_CONTROL.reset): Define a safe restart state. Algorithm-specific focus:
/// Field-oriented current-control composition with d/q
/// regulators, decoupling, and modulation interfaces.
ucon_status_t ucon_foc_current_control_reset(const ucon_algorithm_scaffold_call_t *call);

/// Update flux, torque, angle, or speed estimates.
/// TODO(FOC_CURRENT_CONTROL.estimate_motor_state): State model validity and low-speed
/// operating limits. Algorithm-specific
/// focus: Field-oriented current-control
/// composition with d/q regulators,
/// decoupling, and modulation interfaces.
ucon_status_t ucon_foc_current_control_estimate_motor_state(const ucon_algorithm_scaffold_call_t *call);

/// Compute d/q or switching-state command.
/// TODO(FOC_CURRENT_CONTROL.compute_current_command): Define decoupling, saturation, and
/// current-limit policy.
/// Algorithm-specific focus:
/// Field-oriented current-control
/// composition with d/q regulators,
/// decoupling, and modulation interfaces.
ucon_status_t ucon_foc_current_control_compute_current_command(const ucon_algorithm_scaffold_call_t *call);

/// Map abstract command into declared modulation values.
/// TODO(FOC_CURRENT_CONTROL.modulate): Do not assume gate polarity, dead time, or timer
/// setup. Algorithm-specific focus: Field-oriented
/// current-control composition with d/q regulators,
/// decoupling, and modulation interfaces.
ucon_status_t ucon_foc_current_control_modulate(const ucon_algorithm_scaffold_call_t *call);

/// Coordinate one synchronized motor-control update.
/// TODO(FOC_CURRENT_CONTROL.step): Bound work and preserve outputs on invalid measurements.
/// Algorithm-specific focus: Field-oriented current-control
/// composition with d/q regulators, decoupling, and
/// modulation interfaces.
ucon_status_t ucon_foc_current_control_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_FOC_CURRENT_CONTROL_H */
