/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/infrastructure/fault_detection/sensor_fdi.h
/// @brief Initial-wave fail-closed module outline for SENSOR_FDI.
#ifndef UEF_UCON_SCAFFOLD_SENSOR_FDI_H
#define UEF_UCON_SCAFFOLD_SENSOR_FDI_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Generic residual monitoring, persistence, and configured fault-isolation masks; plant residual models and fault hypotheses are caller supplied.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: FIRST_PASS.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check residual channels, thresholds, persistence, and isolation masks.
/// TODO(SENSOR_FDI.validate_config): Keep residual models and fault policy caller-owned.
/// Algorithm-specific focus: Generic residual monitoring,
/// persistence, and configured fault-isolation masks; plant
/// residual models and fault hypotheses are caller
/// supplied.
ucon_status_t ucon_sensor_fdi_validate_config(const ucon_algorithm_scaffold_call_t *call);

/// Initialize counters and diagnostic outputs.
/// TODO(SENSOR_FDI.init): Define startup grace and initial fault state. Algorithm-specific
/// focus: Generic residual monitoring, persistence, and configured
/// fault-isolation masks; plant residual models and fault hypotheses
/// are caller supplied.
ucon_status_t ucon_sensor_fdi_init(const ucon_algorithm_scaffold_call_t *call);

/// Clear/rearm diagnostic channels.
/// TODO(SENSOR_FDI.reset): Specify whether latched faults require an explicit clear.
/// Algorithm-specific focus: Generic residual monitoring,
/// persistence, and configured fault-isolation masks; plant residual
/// models and fault hypotheses are caller supplied.
ucon_status_t ucon_sensor_fdi_reset(const ucon_algorithm_scaffold_call_t *call);

/// Consume caller-supplied residuals and validity flags.
/// TODO(SENSOR_FDI.update_residuals): Separate missing/bad data from a physical fault
/// indication. Algorithm-specific focus: Generic residual
/// monitoring, persistence, and configured fault-isolation
/// masks; plant residual models and fault hypotheses are
/// caller supplied.
ucon_status_t ucon_sensor_fdi_update_residuals(const ucon_algorithm_scaffold_call_t *call);

/// Apply persistence and configured isolation rules.
/// TODO(SENSOR_FDI.update_fault_state): Do not claim root cause without explicit hypotheses.
/// Algorithm-specific focus: Generic residual
/// monitoring, persistence, and configured
/// fault-isolation masks; plant residual models and
/// fault hypotheses are caller supplied.
ucon_status_t ucon_sensor_fdi_update_fault_state(const ucon_algorithm_scaffold_call_t *call);

/// Publish one bounded diagnostic update.
/// TODO(SENSOR_FDI.step): Do not actuate or silently choose a fallback. Algorithm-specific
/// focus: Generic residual monitoring, persistence, and configured
/// fault-isolation masks; plant residual models and fault hypotheses
/// are caller supplied.
ucon_status_t ucon_sensor_fdi_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_SENSOR_FDI_H */
