/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/future/signal_processing/resampling/cic_decimator.h
/// @brief Future-wave fail-closed module outline for CIC_DECIMATOR.
#ifndef UEF_UCON_SCAFFOLD_CIC_DECIMATOR_H
#define UEF_UCON_SCAFFOLD_CIC_DECIMATOR_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Cascaded-integrator-comb decimator with configured rate change, stage count, and differential delay.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: PLANNED.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check transform/statistic/rate dimensions and numeric range.
/// TODO(CIC_DECIMATOR.validate_config): Define sample layout, scale, rate, and fixed buffer
/// size. Algorithm-specific focus:
/// Cascaded-integrator-comb decimator with configured
/// rate change, stage count, and differential delay.
ucon_status_t ucon_cic_decimator_validate_config(const ucon_algorithm_scaffold_call_t *call);

/// Initialize window, phase, ring buffer, and accumulator.
/// TODO(CIC_DECIMATOR.init): Define warm-up and reset behavior. Algorithm-specific focus:
/// Cascaded-integrator-comb decimator with configured rate change,
/// stage count, and differential delay.
ucon_status_t ucon_cic_decimator_init(const ucon_algorithm_scaffold_call_t *call);

/// Clear signal history and phase/index state.
/// TODO(CIC_DECIMATOR.reset): State ownership of coefficient/window tables.
/// Algorithm-specific focus: Cascaded-integrator-comb decimator
/// with configured rate change, stage count, and differential
/// delay.
ucon_status_t ucon_cic_decimator_reset(const ucon_algorithm_scaffold_call_t *call);

/// Process one bounded block or fixed-rate sample group.
/// TODO(CIC_DECIMATOR.process_block): Define latency, overlap, scaling, and overflow
/// behavior. Algorithm-specific focus:
/// Cascaded-integrator-comb decimator with configured rate
/// change, stage count, and differential delay.
ucon_status_t ucon_cic_decimator_process_block(const ucon_algorithm_scaffold_call_t *call);

/// Advance the algorithm and publish output/validity metadata.
/// TODO(CIC_DECIMATOR.step): Specify incomplete-block and dropped-sample behavior.
/// Algorithm-specific focus: Cascaded-integrator-comb decimator
/// with configured rate change, stage count, and differential
/// delay.
ucon_status_t ucon_cic_decimator_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_CIC_DECIMATOR_H */
