/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/control/tuning/pid_autotune.h
/// @brief Initial-wave fail-closed module outline for PID_AUTOTUNE.
#ifndef UEF_UCON_SCAFFOLD_PID_AUTOTUNE_H
#define UEF_UCON_SCAFFOLD_PID_AUTOTUNE_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Supervised PID tuning utility using a named relay or response-based experiment; it must not change gains implicitly during operation.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: PLANNED.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check tuning mode, safe excitation bounds, and stop conditions.
/// TODO(PID_AUTOTUNE.validate_experiment): Require explicit supervision; never launch an
/// experiment implicitly. Algorithm-specific focus:
/// Supervised PID tuning utility using a named relay
/// or response-based experiment; it must not change
/// gains implicitly during operation.
ucon_status_t ucon_pid_autotune_validate_experiment(const ucon_algorithm_scaffold_call_t *call);

/// Initialize experiment and result state.
/// TODO(PID_AUTOTUNE.init): Define prior gain snapshot and abort behavior. Algorithm-specific
/// focus: Supervised PID tuning utility using a named relay or
/// response-based experiment; it must not change gains implicitly
/// during operation.
ucon_status_t ucon_pid_autotune_init(const ucon_algorithm_scaffold_call_t *call);

/// Abort/rearm tuning and restore the documented gain state.
/// TODO(PID_AUTOTUNE.reset): Specify what happens after invalid or interrupted data.
/// Algorithm-specific focus: Supervised PID tuning utility using a
/// named relay or response-based experiment; it must not change
/// gains implicitly during operation.
ucon_status_t ucon_pid_autotune_reset(const ucon_algorithm_scaffold_call_t *call);

/// Collect bounded input/output data for the selected tuning method.
/// TODO(PID_AUTOTUNE.collect_response): Define sample synchronization, noise rejection, and
/// excitation limits. Algorithm-specific focus:
/// Supervised PID tuning utility using a named relay or
/// response-based experiment; it must not change gains
/// implicitly during operation.
ucon_status_t ucon_pid_autotune_collect_response(const ucon_algorithm_scaffold_call_t *call);

/// Compute gains from the named relay/response-based rule.
/// TODO(PID_AUTOTUNE.estimate_parameters): State exact formula, validity range, and
/// confidence/rejection criteria. Algorithm-specific
/// focus: Supervised PID tuning utility using a named
/// relay or response-based experiment; it must not
/// change gains implicitly during operation.
ucon_status_t ucon_pid_autotune_estimate_parameters(const ucon_algorithm_scaffold_call_t *call);

/// Return proposed gains for explicit caller review/application.
/// TODO(PID_AUTOTUNE.publish_candidate): Do not write live controller gains automatically.
/// Algorithm-specific focus: Supervised PID tuning
/// utility using a named relay or response-based
/// experiment; it must not change gains implicitly
/// during operation.
ucon_status_t ucon_pid_autotune_publish_candidate(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_PID_AUTOTUNE_H */
