/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/future/estimators/identification/recursive_arma.h
/// @brief Future-wave fail-closed module outline for RECURSIVE_ARMA.
#ifndef UEF_UCON_SCAFFOLD_RECURSIVE_ARMA_H
#define UEF_UCON_SCAFFOLD_RECURSIVE_ARMA_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Online parameter estimation for an autoregressive moving-average time-series model.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: PLANNED.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check model order, delays, regressor layout, and parameter bounds.
/// TODO(RECURSIVE_ARMA.validate_model): Document identifiability assumptions and fixed
/// covariance/history size. Algorithm-specific focus:
/// Online parameter estimation for an autoregressive
/// moving-average time-series model.
ucon_status_t ucon_recursive_arma_validate_model(const ucon_algorithm_scaffold_call_t *call);

/// Initialize parameters and information/covariance state.
/// TODO(RECURSIVE_ARMA.init): Define P0, forgetting/regularization, and parameter seed.
/// Algorithm-specific focus: Online parameter estimation for an
/// autoregressive moving-average time-series model.
ucon_status_t ucon_recursive_arma_init(const ucon_algorithm_scaffold_call_t *call);

/// Reset recursive memory under a documented parameter policy.
/// TODO(RECURSIVE_ARMA.reset): State whether reset retains or reinitializes parameters.
/// Algorithm-specific focus: Online parameter estimation for an
/// autoregressive moving-average time-series model.
ucon_status_t ucon_recursive_arma_reset(const ucon_algorithm_scaffold_call_t *call);

/// Build ordered regressors, instruments, and sensitivity terms.
/// TODO(RECURSIVE_ARMA.build_regressor): Pin signal sign/order/delay and reject
/// stale/non-finite samples. Algorithm-specific focus:
/// Online parameter estimation for an autoregressive
/// moving-average time-series model.
ucon_status_t ucon_recursive_arma_build_regressor(const ucon_algorithm_scaffold_call_t *call);

/// Apply one bounded recursive parameter update.
/// TODO(RECURSIVE_ARMA.update_parameters): Define forgetting, conditioning, symmetrization,
/// and projection. Algorithm-specific focus: Online
/// parameter estimation for an autoregressive
/// moving-average time-series model.
ucon_status_t ucon_recursive_arma_update_parameters(const ucon_algorithm_scaffold_call_t *call);

/// Report residual and excitation/conditioning status.
/// TODO(RECURSIVE_ARMA.get_diagnostics): Distinguish insufficient excitation from
/// numeric/model failure. Algorithm-specific focus:
/// Online parameter estimation for an autoregressive
/// moving-average time-series model.
ucon_status_t ucon_recursive_arma_get_diagnostics(const ucon_algorithm_scaffold_call_t *call);

/// Consume one aligned sample and atomically publish the updated model.
/// TODO(RECURSIVE_ARMA.step): Bound loops and preserve state on failure. Algorithm-specific
/// focus: Online parameter estimation for an autoregressive
/// moving-average time-series model.
ucon_status_t ucon_recursive_arma_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_RECURSIVE_ARMA_H */
