/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/future/electrical/motor_control/sensorless_foc_observer.h
/// @brief Future-wave fail-closed module outline for SENSORLESS_FOC_OBSERVER.
#ifndef UEF_UCON_SCAFFOLD_SENSORLESS_FOC_OBSERVER_H
#define UEF_UCON_SCAFFOLD_SENSORLESS_FOC_OBSERVER_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Sensorless motor-state observer supplying the electrical angle/speed needed by a declared FOC profile.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: PLANNED.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check motor model, transform, sample timing, and current/voltage limits.
/// TODO(SENSORLESS_FOC_OBSERVER.validate_config): State motor type and angle-source validity.
/// Algorithm-specific focus: Sensorless
/// motor-state observer supplying the
/// electrical angle/speed needed by a declared
/// FOC profile.
ucon_status_t ucon_sensorless_foc_observer_validate_config(const ucon_algorithm_scaffold_call_t *call);

/// Initialize d/q loops, flux/torque estimate, and modulation state.
/// TODO(SENSORLESS_FOC_OBSERVER.init): Define alignment and sensor-offset ownership.
/// Algorithm-specific focus: Sensorless motor-state
/// observer supplying the electrical angle/speed needed
/// by a declared FOC profile.
ucon_status_t ucon_sensorless_foc_observer_init(const ucon_algorithm_scaffold_call_t *call);

/// Reset control/estimator history without issuing gate actions.
/// TODO(SENSORLESS_FOC_OBSERVER.reset): Define a safe restart state. Algorithm-specific
/// focus: Sensorless motor-state observer supplying the
/// electrical angle/speed needed by a declared FOC
/// profile.
ucon_status_t ucon_sensorless_foc_observer_reset(const ucon_algorithm_scaffold_call_t *call);

/// Update flux, torque, angle, or speed estimates.
/// TODO(SENSORLESS_FOC_OBSERVER.estimate_motor_state): State model validity and low-speed
/// operating limits. Algorithm-specific
/// focus: Sensorless motor-state observer
/// supplying the electrical angle/speed
/// needed by a declared FOC profile.
ucon_status_t ucon_sensorless_foc_observer_estimate_motor_state(const ucon_algorithm_scaffold_call_t *call);

/// Compute d/q or switching-state command.
/// TODO(SENSORLESS_FOC_OBSERVER.compute_current_command): Define decoupling, saturation, and
/// current-limit policy.
/// Algorithm-specific focus:
/// Sensorless motor-state observer
/// supplying the electrical
/// angle/speed needed by a declared
/// FOC profile.
ucon_status_t ucon_sensorless_foc_observer_compute_current_command(const ucon_algorithm_scaffold_call_t *call);

/// Map abstract command into declared modulation values.
/// TODO(SENSORLESS_FOC_OBSERVER.modulate): Do not assume gate polarity, dead time, or timer
/// setup. Algorithm-specific focus: Sensorless
/// motor-state observer supplying the electrical
/// angle/speed needed by a declared FOC profile.
ucon_status_t ucon_sensorless_foc_observer_modulate(const ucon_algorithm_scaffold_call_t *call);

/// Coordinate one synchronized motor-control update.
/// TODO(SENSORLESS_FOC_OBSERVER.step): Bound work and preserve outputs on invalid
/// measurements. Algorithm-specific focus: Sensorless
/// motor-state observer supplying the electrical
/// angle/speed needed by a declared FOC profile.
ucon_status_t ucon_sensorless_foc_observer_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_SENSORLESS_FOC_OBSERVER_H */
