/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/electrical/grid/droop_control.h
/// @brief Initial-wave fail-closed module outline for DROOP_CONTROL.
#ifndef UEF_UCON_SCAFFOLD_DROOP_CONTROL_H
#define UEF_UCON_SCAFFOLD_DROOP_CONTROL_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// P-f/Q-V droop laws with declared grid-forming or parallel-inverter model and limits.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: FIRST_PASS.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check phase sequence, nominal frequency, gains, and grid limits.
/// TODO(DROOP_CONTROL.validate_config): Declare sequence and per-unit/scaling conventions.
/// Algorithm-specific focus: P-f/Q-V droop laws with
/// declared grid-forming or parallel-inverter model and
/// limits.
ucon_status_t ucon_droop_control_validate_config(const ucon_algorithm_scaffold_call_t *call);

/// Initialize orthogonal-signal, sequence, phase, and loop states.
/// TODO(DROOP_CONTROL.init): Define phase seed and acquisition range. Algorithm-specific
/// focus: P-f/Q-V droop laws with declared grid-forming or
/// parallel-inverter model and limits.
ucon_status_t ucon_droop_control_init(const ucon_algorithm_scaffold_call_t *call);

/// Clear synchronization history and lock persistence.
/// TODO(DROOP_CONTROL.reset): Define loss-of-lock and restart behavior. Algorithm-specific
/// focus: P-f/Q-V droop laws with declared grid-forming or
/// parallel-inverter model and limits.
ucon_status_t ucon_droop_control_reset(const ucon_algorithm_scaffold_call_t *call);

/// Update SOGI/sequence or synchronous-frame signal estimates.
/// TODO(DROOP_CONTROL.update_signal_model): Specify frequency adaptation and sample-time
/// coupling. Algorithm-specific focus: P-f/Q-V droop
/// laws with declared grid-forming or
/// parallel-inverter model and limits.
ucon_status_t ucon_droop_control_update_signal_model(const ucon_algorithm_scaffold_call_t *call);

/// Update phase/frequency and lock/quality state.
/// TODO(DROOP_CONTROL.update_loop): Define anti-windup, bounds, and units. Algorithm-specific
/// focus: P-f/Q-V droop laws with declared grid-forming or
/// parallel-inverter model and limits.
ucon_status_t ucon_droop_control_update_loop(const ucon_algorithm_scaffold_call_t *call);

/// Process one grid sample and publish synchronization outputs.
/// TODO(DROOP_CONTROL.step): Reject invalid amplitude/sequence inputs without poisoning
/// state. Algorithm-specific focus: P-f/Q-V droop laws with
/// declared grid-forming or parallel-inverter model and limits.
ucon_status_t ucon_droop_control_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_DROOP_CONTROL_H */
