/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/future/estimators/observers/sliding_mode_observer.h
/// @brief Future-wave fail-closed module outline for SLIDING_MODE_OBSERVER.
#ifndef UEF_UCON_SCAFFOLD_SLIDING_MODE_OBSERVER_H
#define UEF_UCON_SCAFFOLD_SLIDING_MODE_OBSERVER_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Sliding-mode state observer with an explicit output injection and convergence assumptions.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: PLANNED.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check plant matrices, dimensions, gain layout, and disturbance model.
/// TODO(SLIDING_MODE_OBSERVER.validate_model): Implementation sequence: 1) Validate pointers,
/// configuration, dimensions, and preconditions
/// before writing outputs or state. 2) Check
/// plant matrices, dimensions, gain layout, and
/// disturbance model. 3) Check numeric results,
/// declared constraints, and fixed work/memory
/// bounds. 4) Commit outputs, state, and
/// diagnostics together only after success;
/// preserve prior values on failure.
/// Operation-specific requirements: State
/// detectability/observability assumptions and
/// gain ownership. Algorithm-specific focus:
/// Sliding-mode state observer with an explicit
/// output injection and convergence assumptions.
ucon_status_t ucon_sliding_mode_observer_validate_model(const ucon_algorithm_scaffold_call_t *call);

/// Initialize estimate and observer/disturbance states.
/// TODO(SLIDING_MODE_OBSERVER.init): Implementation sequence: 1) Validate pointers,
/// configuration, dimensions, and preconditions before
/// writing outputs or state. 2) Initialize estimate and
/// observer/disturbance states. 3) Check numeric results,
/// declared constraints, and fixed work/memory bounds. 4)
/// Commit outputs, state, and diagnostics together only
/// after success; preserve prior values on failure.
/// Operation-specific requirements: Define initial estimate
/// and any required output history. Algorithm-specific
/// focus: Sliding-mode state observer with an explicit
/// output injection and convergence assumptions.
ucon_status_t ucon_sliding_mode_observer_init(const ucon_algorithm_scaffold_call_t *call);

/// Clear observer history or preload a documented state.
/// TODO(SLIDING_MODE_OBSERVER.reset): Implementation sequence: 1) Validate pointers,
/// configuration, dimensions, and preconditions before
/// writing outputs or state. 2) Clear observer history or
/// preload a documented state. 3) Check numeric results,
/// declared constraints, and fixed work/memory bounds. 4)
/// Commit outputs, state, and diagnostics together only
/// after success; preserve prior values on failure.
/// Operation-specific requirements: Specify bumpless reset
/// and disturbance estimate handling. Algorithm-specific
/// focus: Sliding-mode state observer with an explicit
/// output injection and convergence assumptions.
ucon_status_t ucon_sliding_mode_observer_reset(const ucon_algorithm_scaffold_call_t *call);

/// Propagate the model and predicted state.
/// TODO(SLIDING_MODE_OBSERVER.predict): Implementation sequence: 1) Validate pointers,
/// configuration, dimensions, and preconditions before
/// writing outputs or state. 2) Propagate the model and
/// predicted state. 3) Check numeric results, declared
/// constraints, and fixed work/memory bounds. 4) Commit
/// outputs, state, and diagnostics together only after
/// success; preserve prior values on failure.
/// Operation-specific requirements: Define sample time
/// and discretization. Algorithm-specific focus:
/// Sliding-mode state observer with an explicit output
/// injection and convergence assumptions.
ucon_status_t ucon_sliding_mode_observer_predict(const ucon_algorithm_scaffold_call_t *call);

/// Apply measured output/residual and observer injection.
/// TODO(SLIDING_MODE_OBSERVER.correct): Implementation sequence: 1) Validate pointers,
/// configuration, dimensions, and preconditions before
/// writing outputs or state. 2) Apply measured
/// output/residual and observer injection. 3) Check
/// numeric results, declared constraints, and fixed
/// work/memory bounds. 4) Commit outputs, state, and
/// diagnostics together only after success; preserve
/// prior values on failure. Operation-specific
/// requirements: Specify residual sign, disturbance
/// channels, and gain convention. Algorithm-specific
/// focus: Sliding-mode state observer with an explicit
/// output injection and convergence assumptions.
ucon_status_t ucon_sliding_mode_observer_correct(const ucon_algorithm_scaffold_call_t *call);

/// Run one observer update and report estimate/residual validity.
/// TODO(SLIDING_MODE_OBSERVER.step): Implementation sequence: 1) Validate pointers,
/// configuration, dimensions, and preconditions before
/// writing outputs or state. 2) Run one observer update and
/// report estimate/residual validity. 3) Check numeric
/// results, declared constraints, and fixed work/memory
/// bounds. 4) Commit outputs, state, and diagnostics
/// together only after success; preserve prior values on
/// failure. Operation-specific requirements: Bound work and
/// preserve prior state after numeric failure.
/// Algorithm-specific focus: Sliding-mode state observer
/// with an explicit output injection and convergence
/// assumptions.
ucon_status_t ucon_sliding_mode_observer_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_SLIDING_MODE_OBSERVER_H */
