/// Generated by tools/generate_ucon_scaffolds.py.
/// @file include/uef/ucon/future/electrical/power_conversion/hysteretic_current_control.h
/// @brief Future-wave fail-closed module outline for HYSTERETIC_CURRENT_CONTROL.
#ifndef UEF_UCON_SCAFFOLD_HYSTERETIC_CURRENT_CONTROL_H
#define UEF_UCON_SCAFFOLD_HYSTERETIC_CURRENT_CONTROL_H
#include <uef/ucon/detail/algorithm_call.h>
#ifdef __cplusplus
extern "C" {
#endif

/// Hysteresis-band current controller that selects switching actions from current error and configured bounds.
/// Development outline only; this is not a typed or usable algorithm API.
/// Roadmap priority: PLANNED.
/// Every operation returns UCON_NOT_IMPLEMENTED until its contract is reviewed.

/// Check converter topology, sensor polarity, and switch map.
/// TODO(HYSTERETIC_CURRENT_CONTROL.validate_topology): The algorithm key does not define a
/// power-stage model. Algorithm-specific
/// focus: Hysteresis-band current
/// controller that selects switching
/// actions from current error and
/// configured bounds.
ucon_status_t ucon_hysteretic_current_control_validate_topology(const ucon_algorithm_scaffold_call_t *call);

/// Initialize current/reference and switching-cycle state.
/// TODO(HYSTERETIC_CURRENT_CONTROL.init): Define cycle phase and hardware interlock
/// requirements. Algorithm-specific focus:
/// Hysteresis-band current controller that selects
/// switching actions from current error and configured
/// bounds.
ucon_status_t ucon_hysteretic_current_control_init(const ucon_algorithm_scaffold_call_t *call);

/// Clear controller history without producing a gate action.
/// TODO(HYSTERETIC_CURRENT_CONTROL.reset): Safe-state handling belongs to caller/target
/// supervision. Algorithm-specific focus:
/// Hysteresis-band current controller that selects
/// switching actions from current error and
/// configured bounds.
ucon_status_t ucon_hysteretic_current_control_reset(const ucon_algorithm_scaffold_call_t *call);

/// Predict current/state under allowed switch actions.
/// TODO(HYSTERETIC_CURRENT_CONTROL.predict_current): Derive equations and sample timing from
/// the selected topology.
/// Algorithm-specific focus:
/// Hysteresis-band current controller that
/// selects switching actions from current
/// error and configured bounds.
ucon_status_t ucon_hysteretic_current_control_predict_current(const ucon_algorithm_scaffold_call_t *call);

/// Choose an action under the named objective/constraints.
/// TODO(HYSTERETIC_CURRENT_CONTROL.select_command): Define dead time, current limits, and
/// deterministic tie-breaking.
/// Algorithm-specific focus: Hysteresis-band
/// current controller that selects switching
/// actions from current error and configured
/// bounds.
ucon_status_t ucon_hysteretic_current_control_select_command(const ucon_algorithm_scaffold_call_t *call);

/// Run one bounded converter update and return an abstract command.
/// TODO(HYSTERETIC_CURRENT_CONTROL.step): Keep physical gate sequencing in the target
/// boundary. Algorithm-specific focus: Hysteresis-band
/// current controller that selects switching actions
/// from current error and configured bounds.
ucon_status_t ucon_hysteretic_current_control_step(const ucon_algorithm_scaffold_call_t *call);

#ifdef __cplusplus
}
#endif

#endif /* UEF_UCON_SCAFFOLD_HYSTERETIC_CURRENT_CONTROL_H */
